# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_dev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
